"""add_cricketer_table_session_question_ids

Revision ID: e425cd27d2a8
Revises: 3506816003f2
Create Date: 2026-09-12 12:22:41.063035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e425cd27d2a8'
down_revision: Union[str, None] = '3506816003f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cricketers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cricketers_name'), 'cricketers', ['name'], unique=True)
    op.add_column('game_answers', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('player_sessions', sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_sessions', 'question_ids')
    op.drop_column('game_answers', 'attempt_number')
    op.drop_index(op.f('ix_cricketers_name'), table_name='cricketers')
    op.drop_table('cricketers')
    # ### end Alembic commands ###
