/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PlayGuessRouteImport } from './routes/play.guess'
import { Route as PlayUnscrambleRouteImport } from './routes/play.unscramble'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGuessRoute = PlayGuessRouteImport.update({
  id: '/play/guess',
  path: '/play/guess',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayUnscrambleRoute = PlayUnscrambleRouteImport.update({
  id: '/play/unscramble',
  path: '/play/unscramble',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/signin': typeof SigninRoute
  '/play/guess': typeof PlayGuessRoute
  '/play/unscramble': typeof PlayUnscrambleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/signin': typeof SigninRoute
  '/play/guess': typeof PlayGuessRoute
  '/play/unscramble': typeof PlayUnscrambleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/signin': typeof SigninRoute
  '/play/guess': typeof PlayGuessRoute
  '/play/unscramble': typeof PlayUnscrambleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/games'
    | '/leaderboard'
    | '/signin'
    | '/play/guess'
    | '/play/unscramble'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/games'
    | '/leaderboard'
    | '/signin'
    | '/play/guess'
    | '/play/unscramble'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/games'
    | '/leaderboard'
    | '/signin'
    | '/play/guess'
    | '/play/unscramble'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SigninRoute: typeof SigninRoute
  PlayGuessRoute: typeof PlayGuessRoute
  PlayUnscrambleRoute: typeof PlayUnscrambleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/guess': {
      id: '/play/guess'
      path: '/play/guess'
      fullPath: '/play/guess'
      preLoaderRoute: typeof PlayGuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/unscramble': {
      id: '/play/unscramble'
      path: '/play/unscramble'
      fullPath: '/play/unscramble'
      preLoaderRoute: typeof PlayUnscrambleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  SigninRoute: SigninRoute,
  PlayGuessRoute: PlayGuessRoute,
  PlayUnscrambleRoute: PlayUnscrambleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
